# SPDX-License-Identifier: Apache-2.0
# semrel plugin configuration — keeps releases in 0.x.x until deliberately promoted.
# To release 1.0.0: remove version_ceiling and commit.

tagPrefix: "v"
version_ceiling: "1.0.0"
ceiling_strategy: clamp
commit_changelog: false
tag_exists_strategy: update-changelog

branches:
  - name: main
